source("配置.R", encoding = "UTF-8")
setup_script_env()
cat("=== ", DATASET, " bulk RNA-seq 分析 ===\n\n")
source("01_下载数据.R", encoding = "UTF-8")
source("02_差异分析.R", encoding = "UTF-8")
source("03_细胞比例估算.R", encoding = "UTF-8")
source("04_可视化.R", encoding = "UTF-8")
source("06_补充图.R", encoding = "UTF-8")
cat("\n=== 分析完成 ===\n")
