source("配置.R", encoding = "UTF-8")
setup_script_env()
cat("=== ", DATASET, " scRNA-seq 分析 ===\n\n")
source("01_下载数据.R", encoding = "UTF-8")
source("02_单细胞预处理.R", encoding = "UTF-8")
source("03_细胞类型注释.R", encoding = "UTF-8")
source("03_pseudobulk差异分析.R", encoding = "UTF-8")
source("04_可视化.R", encoding = "UTF-8")
source("05_富集分析.R", encoding = "UTF-8")
source("06_补充图.R", encoding = "UTF-8")
cat("\n=== 分析完成 ===\n")
