source("配置.R", encoding = "UTF-8")
setup_script_env()
cat("=== GSE171546 脓毒症心肌损伤时序 RNA-seq ===\n\n")
source("01_下载数据.R", encoding = "UTF-8")
source("02_预处理与质控.R", encoding = "UTF-8")
source("03_差异分析.R", encoding = "UTF-8")
source("04_可视化.R", encoding = "UTF-8")
source("05_富集分析.R", encoding = "UTF-8")
cat("\n=== 分析完成 ===\n")
